# Generated by Django 4.1 on 2022-08-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_madre_sobrina_sobrino_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrina',
            name='examenes',
            field=models.ImageField(upload_to=''),
        ),
    ]
