# Generated by Django 4.1 on 2022-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_renault_delete_madre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('velocidad', models.ImageField(upload_to='')),
                ('caballos_fuerza', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('velocidad', models.ImageField(upload_to='')),
                ('caballos_fuerza', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Sobrina',
        ),
        migrations.DeleteModel(
            name='Sobrino',
        ),
    ]
