# Generated by Django 4.1 on 2022-08-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_fiat_ford_delete_sobrina_delete_sobrino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fiat',
            new_name='Volkswagen',
        ),
    ]
