# Generated by Django 4.1 on 2022-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_rename_fiat_volkswagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ford',
            name='caballos_fuerza',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ford',
            name='velocidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='renault',
            name='caballos_fuerza',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='renault',
            name='velocidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volkswagen',
            name='caballos_fuerza',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volkswagen',
            name='velocidad',
            field=models.IntegerField(),
        ),
    ]
